// Code generated by sql2gorm. DO NOT EDIT.
package model

const VsDataRegionTableName = "vs_data_region"

// 全球地区库，采集自腾讯QQ国内+国际版.ADD.JENA.20141221
type VsDataRegion struct {
	ID         uint   `gorm:"column:id;type:int(11) unsigned;primary_key;AUTO_INCREMENT" json:"id"` // 主键
	Pid        uint   `gorm:"column:pid;type:int(11) unsigned;default:0" json:"pid"`                // 父ID
	Path       string `gorm:"column:path;type:varchar(255)" json:"path"`                            // 路径
	Level      uint   `gorm:"column:level;type:int(11) unsigned" json:"level"`                      // 层级
	Name       string `gorm:"column:name;type:varchar(255)" json:"name"`                            // 中文名称
	NameEn     string `gorm:"column:name_en;type:varchar(255)" json:"name_en"`                      // 英文名称
	NamePinyin string `gorm:"column:name_pinyin;type:varchar(255)" json:"name_pinyin"`              // 中文拼音
	Code       string `gorm:"column:code;type:varchar(50)" json:"code"`                             // 代码
}

func (m VsDataRegion) TableName() string {
	return VsDataRegionTableName
}
