// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	_ "fmt"
	"time"
)

const VsIPFlowRecordsTableName = "vs_ip_flow_records"

type VsIPFlowRecords struct {
	ID           uint64    `gorm:"column:id;type:bigint(20);primary_key;AUTO_INCREMENT" json:"id"`
	RecordID     string    `gorm:"column:record_id;type:varchar(100);NOT NULL" json:"record_id"` // 唯一索引，代码里面生成
	Username     string    `gorm:"column:username;type:varchar(100);NOT NULL" json:"username"`
	Password     string    `gorm:"column:password;type:varchar(100);NOT NULL" json:"password"`
	Flow         int64     `gorm:"column:flow;type:bigint(20);default:0;NOT NULL" json:"flow"`         // 流量
	Supplier     string    `gorm:"column:supplier;type:varchar(100);NOT NULL" json:"supplier"`         // 供应商
	UserID       int64     `gorm:"column:user_id;type:bigint(20);NOT NULL" json:"user_id"`             // 系统账号的userid
	ClientIP     string    `gorm:"column:client_ip;type:varchar(50);NOT NULL" json:"client_ip"`        // 客户端ip 白名单的时候才有
	ProxyAddr    string    `gorm:"column:proxy_addr;type:varchar(100);NOT NULL" json:"proxy_addr"`     // 白名单 代理服务器ip端口
	Geo          string    `gorm:"column:geo;type:varchar(20);NOT NULL" json:"geo"`                    // 国家
	AccountID    int64     `gorm:"column:account_id;type:bigint(20);NOT NULL" json:"account_id"`       // 子账号id
	Type         int       `gorm:"column:type;type:tinyint(4);NOT NULL" json:"type"`                   // 模式 1账密 2白名单
	IP           string    `gorm:"column:ip;type:varchar(50);NOT NULL" json:"ip"`                      // 对应代理服务器的ip
	IsDeal       int       `gorm:"column:is_deal;type:tinyint(4);default:0;NOT NULL" json:"is_deal"`   // 是否已经处理 0未处理 1以处理
	DealDatetime time.Time `gorm:"column:deal_datetime;type:datetime" json:"deal_datetime"`            // 处理的时间
	Unix         int64     `gorm:"column:unix;type:bigint(20);default:0;NOT NULL" json:"unix"`         // 流量上报的时间
	IsDatacenter bool      `gorm:"column:is_datacenter;type:tinyint(1);NOT NULL" json:"is_datacenter"` // 是否是静态机房流量
	FlowDatetime time.Time `gorm:"column:flow_datetime;type:datetime" json:"flow_datetime"`            // 流量上报的时间
}

func (m VsIPFlowRecords) TableName() string {
	return VsIPFlowRecordsTableName

}
