// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

const VsIPTransitDynamicTableName = "vs_ip_transit_dynamic"

// 动态ip用户数据表
type VsIPTransitDynamic struct {
	ID                     int64      `gorm:"column:id;type:bigint(20);primary_key;AUTO_INCREMENT" json:"id"`                                     // 主键id
	UserID                 int64      `gorm:"column:user_id;type:bigint(20);NOT NULL" json:"user_id"`                                             // 用户id
	UseFlow                uint64     `gorm:"column:use_flow;type:bigint(20) unsigned;default:0;NOT NULL" json:"use_flow"`                        // 已使用流量（单位B）
	ResidualFlow           int64      `gorm:"column:residual_flow;type:bigint(20);default:0;NOT NULL" json:"residual_flow"`                       // 剩余流量（单位B）
	UseFlowDatacenter      uint64     `gorm:"column:use_flow_datacenter;type:bigint(20) unsigned;default:0;NOT NULL" json:"use_flow_datacenter"`  // 已使用流量（单位B）
	ResidualFlowDatacenter int64      `gorm:"column:residual_flow_datacenter;type:bigint(20);default:0;NOT NULL" json:"residual_flow_datacenter"` // 剩余流量（单位B）
	AutoBuy                string     `gorm:"column:auto_buy;type:char(1);default:0;NOT NULL" json:"auto_buy"`                                    // 1-开启 0-关闭
	LastBuy                int64      `gorm:"column:last_buy;type:bigint(20);default:0;NOT NULL" json:"last_buy"`                                 // 小于流量购买（单位B）自动购买流量开启时生效
	AutoBuyDatacenter      string     `gorm:"column:auto_buy_datacenter;type:char(1);default:0;NOT NULL" json:"auto_buy_datacenter"`              // 1-开启 0-关闭 机房
	LastBuyDatacenter      int64      `gorm:"column:last_buy_datacenter;type:bigint(20);default:0;NOT NULL" json:"last_buy_datacenter"`           // 小于流量购买（单位B）自动购买流量开启时生效 机房
	AutoBuyFlow            int64      `gorm:"column:auto_buy_flow;type:bigint(20);default:0;NOT NULL" json:"auto_buy_flow"`                       // 自动购买流量数量（单位B）
	Whitelist              string     `gorm:"column:whitelist;type:char(1);default:0;NOT NULL" json:"whitelist"`                                  // 是否开启白名单（1-开启0-关闭）
	FlowRecord             string     `gorm:"column:flow_record;type:json" json:"flow_record"`                                                    // 流量更新记录
	AutoBuyPackageID       int64      `gorm:"column:auto_buy_package_id;type:bigint(20)" json:"auto_buy_package_id"`                              // 自动购买套餐id
	AutoBuyDay             string     `gorm:"column:auto_buy_day;type:char(1);default:0;NOT NULL" json:"auto_buy_day"`                            // 按天自动购买（1-开启 0-关闭）
	ExpirationTime         *time.Time `gorm:"column:expiration_time;type:datetime" json:"expiration_time"`                                        // 到期时间
	LastBuyDay             int        `gorm:"column:last_buy_day;type:int(11);default:24;NOT NULL" json:"last_buy_day"`                           // 低于小时（单位小时）自动购买天，开启自动购买生效
	BuyDay                 string     `gorm:"column:buy_day;type:varchar(10)" json:"buy_day"`                                                     // 自动购买时长（eg：1h-一小时 1d-一天）
}

func (m *VsIPTransitDynamic) TableName() string {
	return VsIPTransitDynamicTableName
}

type FlowRecordData struct {
	LastUseFlow                uint64 `json:"last_use_flow"`
	LastResidualFlow           int64  `json:"last_residual_flow"`
	LastUseFlowDatacenter      uint64 `json:"last_use_flow_datacenter"`
	LastResidualFlowDatacenter int64  `json:"last_residual_flow_datacenter"`
	Flow                       int64  `json:"flow"`
	FlowDatacenter             int64  `json:"flowDatacenter"`
	RecordUnix                 int64  `json:"record_unix"`
	LastId                     uint64 `json:"last_id"`
}
